settings:
  title: 'MattDev'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo_icon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'Tous les systèmes sont opérationnels'
  notAllmonitorsOperational: 'Nous rencontrons des problèmes'
  monitorLabelOperational: 'Operationnel'
  monitorLabelNotOperational: 'En panne'
  monitorLabelNoData: 'Données indisponibles'
  dayInHistogramNoData: 'Pas de données'
  dayInHistogramOperational: 'Tout va bien !'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main_website # unique identifier
    name: MattDev.fr
    description: 'Site principal de MattDev' # default=empty
    url: 'https://mattdev.fr' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: cloud_website
    name: Cloud MattDev
    url: 'https://cloud.mattdev.fr'
    method: GET
    expectStatus: 200
    
    - id: mail_service_server
    name: Mails MattDev
    url: 'mail.mattdev.fr'
    method: GET
    expectStatus: 200
    
    - id: ftp_service_server
    name: FTP MattDev
    url: 'ftp.mattdev.fr'
    method: GET
    expectStatus: 200


